// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type Time struct {
	ID        uuid.UUID
	Number    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Time      string
	Scramble  string
	UserID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
